version: '2'

services:
  web:
    build: ./web
    restart: always
    ports:
      - "8000:80"
    environment: 
      - REST_IP=10.5.0.6
    networks: 
      backend:
        ipv4_address: 10.5.0.5
  rest:
    build: ./rest
    restart: always
    environment: 
      - PORT=80
    networks: 
      backend:
        ipv4_address: 10.5.0.6
networks:
  backend:
    driver: "bridge"
    ipam: 
      config: 
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

